### ISSUE TITLE
Fails in minimal test case

### ISSUE THREAD

**Issue by emblem** [madsflensted/elm-brunch#37]
## Problem
```
(venv) soa@glaze:~/BloomcraftProcess/bloomcraft_process/budgeting/client$ brunch -v
2.10.9
(venv) soa@glaze:~/BloomcraftProcess/bloomcraft_process/budgeting/client$ brunch n elm_client
13:22:13 - log: Pulling recent changes from git repo "git://github.com/brunch/dead-simple.git" to "/home/soa/.brunch/skeletons/c76c330b8d54d134fca1e696f29bfc30993e5fd1"...
13:22:13 - log: Pulled master into "/home/soa/.brunch/skeletons/c76c330b8d54d134fca1e696f29bfc30993e5fd1"
13:22:13 - log: Copying local skeleton to "/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client"...
13:22:13 - log: Created skeleton directory layout
13:22:13 - info: Installing packages with npm...
cd elm_client
(venv) soa@glaze:~/BloomcraftProcess/bloomcraft_process/budgeting/client$ cd elm_client
(venv) soa@glaze:~/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client$ npm install --save-dev elm-brunch
brunch-app@0.0.1 /home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client
└── elm-brunch@0.9.0 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
```
Edit brunch-config.js here

```
(venv) soa@glaze:~/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client$ brunch w LOGGY_STACKS=1
/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client/node_modules/graceful-fs/polyfills.js:21
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client/node_modules/graceful-fs/polyfills.js:21:9)
  at Object.keys.reduce.Promise.all.then.setDefaultJobsCount.constructor.process.on.application.loadConfig.then.cfg.then.initCompilation.initWatcher.isConfig.watcher.chokidar.watch.on.error.on.compile.assetErrors.forEach.write.then.watch (/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client/node_modules/brunch/lib/watch.js:377:15)
  at exports.new.start (/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client/node_modules/brunch/lib/index.js:47:28)
  at Command.listener (/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client/node_modules/commander/index.js:301:8)
  at emitTwo (events.js:87:13)
  at Command.emit (events.js:172:7)
  at Command.parseArgs (/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client/node_modules/commander/index.js:615:12)
  at Command.parse (/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client/node_modules/commander/index.js:458:21)
  at Object.exports.run (/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client/node_modules/brunch/lib/cli.js:109:11)
  at Object.<anonymous> (/home/soa/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client/node_modules/brunch/lib/run-cli.js:3:18)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:442:10)
  at startup (node.js:136:18)
  at node.js:966:3

(venv) soa@glaze:~/BloomcraftProcess/bloomcraft_process/budgeting/client/elm_client$ 
```

My brunch-config.js is:
```
// See http://brunch.io for documentation.
exports.files = {
  javascripts: {joinTo: 'app.js'},
  stylesheets: {joinTo: 'app.css'}
};

exports.config.plugins: {
      elmBrunch: {
        // (required) Set to the elm file(s) containing your "main" function `elm make` 
        //            handles all elm dependencies relative to `elmFolder`
        mainModules: ['elm/Main.elm'],
      }
};
```

## Information
- [0.9.0 ] elm-brunch version
- [2.10.9] brunch version
- [4.2.6 ] nodejs version
- [ see above] content of brunch-config.js
- [ none] content of elm-package.json
- [ none in this example] file layout for your elm files relative to root of project.
- [ Ubuntu 16.04] Operating System

**Comment by emblem** [comment]
nvm, user error.
